# Generated by J'Lo - do not edit. Rewritten on every install and update.
#
# zsh dialect. jlo.sh picks this file when the sourcing shell is zsh; the bash
# copy lives beside it. Splitting the two is what lets each one be written for
# a single parser - this file never has to also be valid sh or bash.
jlo() {
  local J arg out
  J="${JLO_HOME-}/bin/jlo-bin"
  # "${1-}", not "$1": a bare `jlo` under a profile running `set -u` would
  # otherwise abort the shell on an unbound parameter before the binary is
  # ever reached - the same rule the autoload hook already follows for
  # $_JLO_LAST_DIR.
  case "${1-}" in
    env|use|selfupdate)
      # The branch below *evaluates* stdout, so help and version output - which
      # clap prints to stdout - must never reach it. Scoped to these three verbs
      # on purpose: a wrapper-wide scan would hijack a child's flags in
      # 'jlo exec -- ./gradlew --help'. env/use take at most a version, and
      # selfupdate takes nothing.
      for arg in "$@"; do
        case "$arg" in
          -h|--help|-V|--version)
            "$J" "$@"
            return
            ;;
        esac
      done
      # Capture, then eval - deliberately not `. <("$J" "$@")`. That form
      # discards the command's exit status in every shell, so the wrapper could
      # not tell a successful 'jlo env' from a failed one. (It is also a hard
      # no-op under the bash 3.2 macOS ships, which the bash copy explains.)
      #
      # The assignment is its own statement: `local out="$(...)"` would report
      # `local`'s status, not the binary's. `|| return` then propagates the
      # failure instead of eval-ing a half-written environment - see the
      # explicit `return 0` in jlo_after_cd, which keeps that status out of the
      # user's prompt.
      #
      # 'selfupdate' rides the same branch: the binary prints the reload line
      # (`. $JLO_HOME/jlo.sh`, plus whichever optional stubs this shell had
      # enabled) on stdout, and eval-ing it replaces the resident jlo function
      # with the one the new binary just generated. An update that was already
      # current prints nothing, so `eval ""` is a no-op.
      out="$("$J" "$@")" || return
      eval "$out"
      ;;
    *)
      "$J" "$@"
      ;;
  esac
}
