# Generated by J'Lo - do not edit. Rewritten on every install and update.
#
# bash dialect of the cd hook. autoload.sh picks this file when the sourcing
# shell is bash. bash has no chpwd, so PROMPT_COMMAND is the only mechanism and
# the dedup bookkeeping below is the price of it; the zsh copy is half the size
# because add-zsh-hook does that work itself. jlo_after_cd is defined further
# down; PROMPT_COMMAND only names it, and nothing runs it before the prompt.

# bash has no add-zsh-hook equivalent, so guard against stacking duplicates
# when this file is sourced again (e.g. `source ~/.bashrc`).
#
# "${PROMPT_COMMAND[@]}" expands a scalar as a single element, so one loop
# recognises an existing registration whether PROMPT_COMMAND is a scalar or
# (bash 5.1+) an array. Matching the ";"-delimited token, not the bare name,
# keeps `echo jlo_after_cd` from passing as the hook itself.
#
# The same loop counts the elements. "${#PROMPT_COMMAND[@]}" would be the
# obvious way, but it has no unset-default form and so aborts a profile
# running under `set -u`; the "-" in the expansion below makes the loop safe
# there, at the cost of yielding one empty word for an unset or empty
# PROMPT_COMMAND - which lands on the scalar branch, exactly where a count of
# 0 did.
_jlo_registered=
_jlo_count=0
for _jlo_cmd in "${PROMPT_COMMAND[@]-}"; do
  _jlo_count=$((_jlo_count + 1))
  case ";$_jlo_cmd;" in
    *";jlo_after_cd;"*) _jlo_registered=1 ;;
  esac
done

if [ -z "$_jlo_registered" ]; then
  if [ "$_jlo_count" -gt 1 ]; then
    # bash 5.1+ runs each array element as its own command; splicing into
    # element 0 would glue our hook onto the user's first one.
    PROMPT_COMMAND=(jlo_after_cd "${PROMPT_COMMAND[@]}")
  else
    # Scalar, unset, or single-element array: a plain assignment adds the
    # hook while preserving the variable's type and export flag.
    PROMPT_COMMAND="jlo_after_cd${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
  fi
fi
unset _jlo_registered _jlo_count _jlo_cmd
