# shellcheck shell=bash
# Generated by J'Lo - do not edit. Rewritten on every install and update.
#
# The cd hook, for bash and zsh alike. Sourced only by those two (the
# autoload.sh stub's guard sees to that), so it need not parse under sh.

# Is there a .jlorc at or above $PWD? Mirrors find_project_config() in
# src/conf.rs: the search stops after $HOME and after a VCS root, both
# inclusive. Kept in shell rather than delegated to jlo-bin because this runs
# on every cd, and a process spawn per directory change is not worth it.
#
# "${dir%/*}" walks up without forking a dirname; it yields "" at the last
# component, hence the "/" fixup.
jlo_find_jlorc() {
  local dir="$PWD"
  # "${HOME%/}": a trailing slash must still stop the walk, as it does in
  # the component-wise Rust compare, or the hook would fire on a .jlorc
  # above HOME that the binary then refuses to read.
  # "${HOME-}" first: a nounset shell without HOME must not abort on a cd.
  local home="${HOME-}"
  home="${home%/}"
  while :; do
    if [ -f "$dir/.jlorc" ]; then
      return 0
    fi
    if [ "$dir" = "$home" ] || [ -e "$dir/.git" ] || [ "$dir" = "/" ]; then
      return 1
    fi
    dir="${dir%/*}"
    [ -n "$dir" ] || dir="/"
  done
}

# The $PWD guard is what keeps this to one run per directory rather than one
# per prompt: bash drives it from PROMPT_COMMAND, which fires before every
# prompt, not only after a cd.
#
# --offline is the whole of "a cd must never start a download": otherwise
# entering a project pinning a missing JDK would stall the shell on ~100MB.
#
# The explicit `return 0` keeps a declined lookup out of `$?`: PROMPT_COMMAND
# runs between the user's command and their prompt, and a hook that reported
# its own failure there would overwrite the status their prompt is showing.
#
# `|| :` is what makes that `return 0` reachable: POSIX exempts every command
# of an AND-OR list from `set -e` *except the last*, so
# `jlo_find_jlorc && jlo env --offline` would exit a `set -e` shell when the
# lookup succeeded and the offline install did not (bash 3.2 and zsh alike).
jlo_after_cd() {
  [ "$PWD" = "${_JLO_LAST_DIR-}" ] && return 0
  _JLO_LAST_DIR="$PWD"
  if jlo_find_jlorc; then
    jlo env --offline || :
  fi
  return 0
}

if [ -n "${ZSH_VERSION-}" ] && command -v setopt >/dev/null 2>&1; then
  # add-zsh-hook is idempotent: re-sourcing this file cannot stack duplicates.
  autoload -U add-zsh-hook
  add-zsh-hook chpwd jlo_after_cd
elif [ -n "${BASH_VERSION-}" ] && command -v shopt >/dev/null 2>&1; then
  # bash has no add-zsh-hook equivalent, so guard against stacking duplicates
  # when this file is sourced again (e.g. `source ~/.bashrc`).
  #
  # "${PROMPT_COMMAND[@]}" expands a scalar as a single element, so one loop
  # recognises an existing registration whether PROMPT_COMMAND is a scalar or
  # (bash 5.1+) an array. Matching the ";"-delimited token, not the bare name,
  # keeps `echo jlo_after_cd` from passing as the hook itself.
  #
  # The same loop counts the elements: "${#PROMPT_COMMAND[@]}" has no
  # unset-default form and aborts under `set -u`. An unset or empty
  # PROMPT_COMMAND yields one empty word, which lands on the scalar branch.
  _jlo_registered=
  _jlo_count=0
  for _jlo_cmd in "${PROMPT_COMMAND[@]-}"; do
    _jlo_count=$((_jlo_count + 1))
    case ";$_jlo_cmd;" in
      *";jlo_after_cd;"*) _jlo_registered=1 ;;
    esac
  done

  if [ -z "$_jlo_registered" ]; then
    if [ "$_jlo_count" -gt 1 ]; then
      # bash 5.1+ runs each array element as its own command; splicing into
      # element 0 would glue our hook onto the user's first one.
      PROMPT_COMMAND=(jlo_after_cd "${PROMPT_COMMAND[@]}")
    else
      # Scalar, unset, or single-element array: a plain assignment adds the
      # hook while preserving the variable's type and export flag.
      # At most one element here, as checked above.
      # shellcheck disable=SC2128,SC2178
      PROMPT_COMMAND="jlo_after_cd${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
    fi
  fi
  unset _jlo_registered _jlo_count _jlo_cmd
fi

# Immediate call for freshly spawned shells. --offline for the same reason as
# in the hook, and more sharply: a download here delays every new terminal.
# Without JLO_HOME there is no default to look for - not '/default.jlorc'.
if jlo_find_jlorc || { [ -n "${JLO_HOME-}" ] && [ -f "$JLO_HOME/default.jlorc" ]; }; then
  _JLO_LAST_DIR="$PWD"
  # `|| :`: this runs while the profile is being sourced, and an
  # unsatisfiable --offline lookup would abort one running under `set -e`.
  jlo env --offline || :
fi

# Read by selfupdate's reload line. Set here, not in the stub, so a 0.2.0
# profile block that sources this file directly sets it too.
_JLO_AUTOLOAD=1
