# Generated by J'Lo - do not edit. Rewritten on every install and update.
#
# The jlo function. The binary writes this one text twice, as jlo-init.bash
# and jlo-init.zsh, and jlo.sh sources the copy named for the sourcing shell:
# it has to parse under bash and zsh alike, but never under a POSIX sh.
jlo() {
  local J out rc=0
  J="${JLO_HOME-}/bin/jlo-bin"
  # "${1-}", not "$1": a bare `jlo` must not abort a `set -u` shell.
  case "${1-}" in
    # The verbs whose stdout is shell code; the others print data there or
    # hand it to a child ('jlo exec -- ./gradlew --help').
    env|use|selfupdate|install|update)
      # install/update may delete the build this shell is on, so the shell
      # must be able to follow.
      if ! ( JAVA_HOME= PATH= ) 2>/dev/null; then
        echo "jlo: JAVA_HOME or PATH is read-only" >&2
        return 1
      fi
      # Capture, then eval - not `. <("$J" ...)`, which discards the exit
      # status in every shell and sources nothing at all under the bash 3.2
      # macOS ships.
      out="$("$J" __wrapped "$@")" || rc=$?
      # Only a payload ending in the marker is evaluated: help, an older
      # binary's refusal and a cut-short payload lack it. A marked payload is
      # evaluated even on failure - the binary writes it before deleting.
      # The marker is cut first: without interactive_comments it is code.
      # `>&1`: zsh's printf reports success on a closed stdout, the
      # redirection does not.
      case "$out" in
        *"# jlo'end") eval "${out%"# jlo'end"}" || [ "$rc" -ne 0 ] || rc=1 ;;
        *) [ "$rc" -ne 0 ] || printf '%s\n' "$out" >&1 || rc=1 ;;
      esac
      return "$rc"
      ;;
    *)
      "$J" "$@"
      ;;
  esac
}
