# Generated by J'Lo - do not edit. Rewritten on every install and update.
#
# zsh dialect of the cd hook. autoload.sh picks this file when the sourcing
# shell is zsh. zsh has chpwd, so registering the hook is two lines - the
# PROMPT_COMMAND bookkeeping bash needs lives only in the bash copy.
# jlo_after_cd is defined further down; add-zsh-hook only records its name.

# add-zsh-hook is idempotent, so re-sourcing this file cannot stack duplicates.
autoload -U add-zsh-hook
add-zsh-hook chpwd jlo_after_cd
