# Generated by J'Lo - do not edit. Rewritten on every install and update.
#
# zsh half of completions.sh, which sources this with the completions
# directory in $_jlo_comp_dir. A file of its own because the stub has to parse
# under a POSIX sh, where the array assignment and (( ... )) below would not.

# Must come before compinit: compinit scans $fpath once, so a user whose
# framework (oh-my-zsh and friends) already ran it gets nothing from this
# line alone - hence the elif below.
fpath=("$_jlo_comp_dir" $fpath)
if (( ! $+functions[compdef] )); then
  autoload -Uz compinit && compinit -i
elif (( ! $+functions[_jlo] )); then
  # compinit already ran, so register after the fact. The autoload is not
  # optional: "compdef _jlo jlo" on its own records the mapping without
  # making _jlo loadable, and completion comes up silently empty.
  autoload -Uz _jlo && compdef _jlo jlo
fi
