# shellcheck shell=bash
# Generated by J'Lo - do not edit. Rewritten on every install and update.
#
# The jlo wrapper function, sourced by jlo.sh under bash and zsh. Plain POSIX
# plus `local`, so one file serves both and a stray `sh` can read it too.
jlo() {
  local J out rc=0
  # jlo.sh exports JLO_HOME before defining this function, but a host can
  # replay the function without the environment it was defined under -
  # a shell rebuilt from a snapshot of functions and PATH, without JLO_HOME.
  # Fall back to the default install, where jlo-bin itself looks; with no
  # HOME either, fail rather than run /bin/jlo-bin. Empty counts as unset.
  if [ -n "${JLO_HOME-}" ]; then
    J="$JLO_HOME/bin/jlo-bin"
  elif [ -n "${HOME-}" ]; then
    J="$HOME/.jlo/bin/jlo-bin"
  else
    echo "jlo: neither JLO_HOME nor HOME is set, so jlo-bin cannot be found" >&2
    return 1
  fi
  # "${1-}", not "$1": a bare `jlo` must not abort a `set -u` shell.
  case "${1-}" in
    # The verbs whose stdout is shell code; the others print data there or
    # hand it to a child ('jlo exec -- ./gradlew --help').
    env|use|selfupdate|install|update)
      # install/update may delete the build this shell is on, so the shell
      # must be able to follow - checked before they touch anything. The
      # others fail loudly in the eval below, and the probe's subshell would
      # cost the cd hook a fork on every directory change.
      case "$1" in
        install|update)
          # Assigned only to probe for readonly.
          # shellcheck disable=SC2034,SC2123
          if ! ( JAVA_HOME='' PATH='' ) 2>/dev/null; then
            echo "jlo: JAVA_HOME or PATH is read-only" >&2
            return 1
          fi
          ;;
      esac
      # Capture, then eval - not `. <("$J" ...)`, which discards the exit
      # status in every shell and sources nothing at all under the bash 3.2
      # macOS ships.
      out="$("$J" __wrapped "$@")" || rc=$?
      # Only a payload ending in the marker is evaluated: help, an older
      # binary's refusal and a cut-short payload lack it. A marked payload is
      # evaluated even on failure - the binary writes it before deleting.
      # The marker is cut first: without interactive_comments it is code.
      # `>&1`: zsh's printf reports success on a closed stdout, the
      # redirection does not.
      case "$out" in
        *"# jlo'end") eval "${out%"# jlo'end"}" || [ "$rc" -ne 0 ] || rc=1 ;;
        *) [ "$rc" -ne 0 ] || printf '%s\n' "$out" >&1 || rc=1 ;;
      esac
      return "$rc"
      ;;
    *)
      "$J" "$@"
      ;;
  esac
}
