//! The hidden install verb: J'Lo owns its own layout under `$JLO_HOME`.
//!
//! The shell code the user sources is not shipped any more. It lives in this
//! repo as real `.zsh`/`.bash` files, is compiled into the binary with
//! `include_str!` (the same mechanism `adoptium.rs` uses for API fixtures), and
//! is written to disk by the verb below. The binary is the shell code's
//! *transport*, not its author: there is one artifact to download and verify,
//! and the files on disk always match the binary that wrote them.
//!
//! The verb is hidden the way `sing` is - intercepted from raw argv before
//! `Cli::parse()`. `hide = true` would only drop it from `--help`:
//! `clap_complete` still emits hidden subcommands into generated completion
//! scripts, and clap's "did you mean" engine still offers it for typos.
//!
//! Publication is ordered: the generated scripts first, the receipt last, so
//! the receipt is the commit marker. `self_heal` below reads it and rewrites
//! the scripts when it names a different version than this binary, with no
//! network and no command for the user to learn. Every file goes down as a
//! temp file plus a `rename` *in its own directory*, so an interruption leaves
//! a stale script rather than a truncated one.
//!
//! What that covers is exactly one state, and the bound is worth stating: an
//! *upgrade* interrupted between the binary and the scripts. A first install
//! interrupted before its first receipt is indistinguishable from an install
//! that predates receipts, and neither is healed - re-running the installer is
//! the documented repair for both, and for anything else the receipt does not
//! speak to.

use crate::ui;
use anyhow::{Context, Result, anyhow};
use serde::{Deserialize, Serialize};
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

/// The argv token that selects this verb. Underscore-prefixed because it is
/// not part of the CLI contract: `install.sh`, `install-local.sh` and (from
/// 0.4.0) `selfupdate` call it, users do not.
pub(crate) const VERB: &str = "__install";

/// Where the install came from. Recorded in the receipt so a later
/// `selfupdate` can tell an install it owns from one a package manager placed.
const DEFAULT_METHOD: &str = "installer";

const VERSION: &str = env!("CARGO_PKG_VERSION");

// The shell sources. Verbatim - the wrappers carry no interpolation at all,
// which is what keeps them shellcheck-able files rather than templates. Only
// the three stubs below are generated with a path baked in.
const INIT_ZSH: &str = include_str!("../shell/jlo-init.zsh");
const INIT_BASH: &str = include_str!("../shell/jlo-init.bash");
const AUTOLOAD_ZSH: &str = include_str!("../shell/jlo-autoload.zsh");
const AUTOLOAD_BASH: &str = include_str!("../shell/jlo-autoload.bash");

/// Picks `bin/jlo-init.$_jlo_d` at source time.
///
/// Only the shell knows which shell it is: `ZSH_VERSION` and `BASH_VERSION`
/// are shell variables, not exported, so the binary that wrote the stub cannot
/// read them. The builtin test is not decoration - nothing stops a user from
/// exporting `ZSH_VERSION`, and a bash child then inherits it *and* sets
/// `BASH_VERSION` itself, so `${ZSH_VERSION:+zsh}${BASH_VERSION:+bash}` yields
/// `zshbash`, names a file that does not exist, and jlo silently fails to
/// initialise. `setopt` and `shopt` are builtins and cannot arrive through the
/// environment.
const DIALECT_DISPATCH: &str = "\
_jlo_d=
if [ -n \"${ZSH_VERSION-}\" ] && command -v setopt >/dev/null 2>&1; then
  _jlo_d=zsh
elif [ -n \"${BASH_VERSION-}\" ] && command -v shopt >/dev/null 2>&1; then
  _jlo_d=bash
fi
";

const GENERATED_HEADER: &str = "\
# Generated by J'Lo - edits are lost on the next install or 'jlo selfupdate'.
";

/// Set by the optional stubs once they have actually loaded, and read by
/// [`print_reload`] to decide what the post-update `eval` re-sources.
///
/// Plain shell variables, deliberately not exported: the question they answer
/// is "did *this* shell opt in?", and an exported one would leak the answer
/// into every child and back out of a subshell that set it.
const AUTOLOAD_MARKER: &str = "_JLO_AUTOLOAD";
const COMPLETIONS_MARKER: &str = "_JLO_COMPLETIONS";

/// The directories and files J'Lo owns under `$JLO_HOME`.
#[derive(Debug)]
pub(crate) struct Layout {
    home: PathBuf,
    bin: PathBuf,
    completions: PathBuf,
}

impl Layout {
    pub(crate) fn new(home: PathBuf) -> Self {
        Self {
            bin: home.join("bin"),
            completions: home.join("completions"),
            home,
        }
    }

    fn receipt(&self) -> PathBuf {
        self.home.join("install-receipt.json")
    }

    pub(crate) fn home(&self) -> &Path {
        &self.home
    }

    /// Where `selfupdate` stages the download: the staging directory has to be
    /// a *sibling* of the binary, because `rename` is only atomic within one
    /// filesystem and `bin/` can itself be a mount point or a symlink.
    pub(crate) fn bin_dir(&self) -> &Path {
        &self.bin
    }

    /// The binary's path, which is also the symlink target.
    ///
    /// The name `jlo-bin` is load-bearing: `~/.local/bin/jlo` is only ever
    /// refreshed when it already points at exactly this path, so renaming the
    /// file would leave every existing user's symlink dangling.
    pub(crate) fn binary(&self) -> PathBuf {
        self.bin.join("jlo-bin")
    }
}

/// `$JLO_HOME/install-receipt.json` - the uv/cargo-dist model.
///
/// Written last, so it is the commit marker for the whole publication. A
/// receipt whose `version` disagrees with the running binary is the
/// known-incomplete state; see [`self_heal`].
#[derive(Debug, Serialize, Deserialize)]
pub(crate) struct Receipt {
    pub(crate) version: String,
    pub(crate) method: String,
    pub(crate) jlo_home: String,
    pub(crate) binary: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    symlink: Option<String>,
}

// ---------------------------------------------------------------------------
// The publication lock
// ---------------------------------------------------------------------------

/// Where the lock file sits. Under `$JLO_HOME`, beside the layout it guards.
const LOCK_FILE: &str = ".selfupdate.lock";

/// An exclusive `flock` under `$JLO_HOME`, held for as long as somebody is
/// writing the layout.
///
/// It lives here rather than in `selfupdate` because *this* is the only code
/// that publishes: `install.sh`, `install-local.sh`, `selfupdate` and the
/// self-heal all end up in [`write_layout`] + [`write_receipt`], and a lock
/// only one of them takes guards nothing. The binary, the generated scripts
/// and the receipt are separate filesystem writes, and no `rename` makes them
/// one transaction.
#[cfg(unix)]
#[derive(Debug)]
pub(crate) struct Lock {
    /// Never read: the lock lives on the open file description, so holding
    /// this alive *is* the whole behaviour. Underscore-prefixed so that stays
    /// legible rather than looking like an oversight.
    _file: fs::File,
}

#[cfg(unix)]
impl Lock {
    /// `None` when somebody else holds it. Fails only when the lock file
    /// itself cannot be opened or locked.
    pub(crate) fn try_acquire(home: &Path) -> Result<Option<Self>> {
        fs::create_dir_all(home).with_context(|| format!("could not create {home:?}"))?;
        let path = home.join(LOCK_FILE);
        let file = fs::OpenOptions::new()
            .create(true)
            .write(true)
            .truncate(false)
            .open(&path)
            .with_context(|| format!("could not open the update lock {path:?}"))?;

        // The lock lives on the open file description, not on the fd number,
        // so it survives `exec` - but only if the fd does. std opens every
        // file `O_CLOEXEC`, which would drop the lock at exactly the moment
        // `selfupdate` is half-published: the new binary in place, its scripts
        // and receipt not yet written. Silently, with no error to report.
        rustix::io::fcntl_setfd(&file, rustix::io::FdFlags::empty())
            .with_context(|| format!("could not keep {path:?} open across exec"))?;

        match rustix::fs::flock(&file, rustix::fs::FlockOperation::NonBlockingLockExclusive) {
            Ok(()) => Ok(Some(Self { _file: file })),
            // Non-blocking on purpose: an unbounded wait on a lock nobody can
            // see is worse than a message, and the self-heal below has
            // somewhere better to go than waiting.
            Err(rustix::io::Errno::WOULDBLOCK) => Ok(None),
            Err(e) => Err(anyhow!("could not lock {path:?}: {e}")),
        }
    }

    /// The same lock, where contention is an error rather than a fork in the
    /// road: two processes must not publish at once.
    pub(crate) fn acquire(home: &Path) -> Result<Self> {
        Self::try_acquire(home)?.ok_or_else(|| {
            anyhow!(
                "another J'Lo install or update is already running (lock file {:?}).",
                home.join(LOCK_FILE)
            )
        })
    }
}

#[cfg(not(unix))]
#[derive(Debug)]
pub(crate) struct Lock;

#[cfg(not(unix))]
impl Lock {
    pub(crate) fn try_acquire(_home: &Path) -> Result<Option<Self>> {
        Ok(None)
    }

    pub(crate) fn acquire(_home: &Path) -> Result<Self> {
        Err(anyhow!(
            "J'Lo cannot lock its install directory on this platform."
        ))
    }
}

// ---------------------------------------------------------------------------
// The verb
// ---------------------------------------------------------------------------

/// Run the install verb. `args` is the raw argv *after* the verb token.
pub(crate) fn cmd_install(args: &[String]) -> Result<()> {
    let mut method = DEFAULT_METHOD.to_string();
    let mut reload = false;
    let mut locked = false;
    let mut rest = args.iter();
    while let Some(arg) = rest.next() {
        match arg.as_str() {
            "--method" => {
                method.clone_from(
                    rest.next()
                        .ok_or_else(|| anyhow!("--method needs a value"))?,
                );
            }
            "--reload" => reload = true,
            "--locked" => locked = true,
            other => return Err(anyhow!("unknown option {other:?} for {VERB}")),
        }
    }

    let layout = Layout::new(crate::jlo_home_dir()?);
    // `selfupdate` `exec`s this verb while already holding the lock, and the
    // fd came across the exec with it. Taking it again from a second open file
    // description would deadlock against ourselves, so the caller says so.
    let _lock = if locked {
        None
    } else {
        Some(Lock::acquire(layout.home())?)
    };
    // Read before writing: the three re-install cases below turn on whether a
    // receipt was already there, and the new one is about to replace it.
    let had_receipt = read_receipt(&layout).is_some();

    write_layout(&layout)?;
    let symlink = ensure_symlink(&layout);
    write_receipt(&layout, &method, symlink.as_deref())?;

    report(&layout, had_receipt, symlink.as_deref());
    if reload {
        print_reload(&layout);
    }
    Ok(())
}

/// The one thing this verb writes to **stdout** (ADR-0001): shell code for the
/// caller to `eval`, which is how the shell that ran `jlo selfupdate` gets the
/// freshly generated wrapper in place of its resident one.
///
/// Only `selfupdate` passes `--reload`. `install.sh` must not: its stdout is
/// not evaluated by anything, and the line would be noise there - the
/// activation block `report` prints is what a bootstrap needs.
///
/// The two optional lines re-source only what this shell had *already*
/// enabled, never more. The signal is the marker each stub sets after it
/// successfully loads: a plain (unexported) shell variable, which is exactly
/// the state the wrapper left behind in this shell and nothing a child process
/// or another session can fake into existence here.
///
/// Every line is a full `if`, not `[ ... ] && . ...`. The last statement's
/// status is the status of the whole `eval`, and a `[ -n ... ]` that is simply
/// false would turn a successful update into a non-zero `jlo selfupdate`.
fn print_reload(layout: &Layout) {
    let jlo_sh = sq(&display(&layout.home.join("jlo.sh")));
    let autoload = sq(&display(&layout.home.join("autoload.sh")));
    let completions = sq(&display(&layout.home.join("completions.sh")));
    crate::ui::print_lines([
        format!(". {jlo_sh}"),
        format!("if [ -n \"${{{AUTOLOAD_MARKER}-}}\" ]; then . {autoload}; fi"),
        format!("if [ -n \"${{{COMPLETIONS_MARKER}-}}\" ]; then . {completions}; fi"),
    ]);
}

/// Everything under `$JLO_HOME` except the binary, the symlink and the receipt.
///
/// Shared with [`self_heal`], which is the whole reason there is no `--repair`
/// verb: the recovery path and the install path are the same code.
///
/// The two optional stubs and the completion scripts warn rather than fail,
/// and the receipt is still written afterwards. That is deliberate, and it is
/// the narrow thing the receipt does *not* promise: it marks which binary
/// published this layout, not that every optional convenience beside it
/// landed. Withholding it instead would overload the one state that already
/// has a meaning - a missing receipt is an install that predates receipts, not
/// a broken one - and would put every later invocation into a rewrite for as
/// long as the underlying write keeps failing. The user gets a warning naming
/// the file, and re-running the installer is the documented repair.
fn write_layout(layout: &Layout) -> Result<()> {
    fs::create_dir_all(&layout.bin)
        .with_context(|| format!("could not create {:?}", layout.bin))?;

    // The wrappers first: the stubs below are what point at them.
    for (name, body) in [
        ("jlo-init.zsh", INIT_ZSH),
        ("jlo-init.bash", INIT_BASH),
        ("jlo-autoload.zsh", AUTOLOAD_ZSH),
        ("jlo-autoload.bash", AUTOLOAD_BASH),
    ] {
        write_atomic(&layout.bin.join(name), body.as_bytes())?;
    }

    write_completions(layout);

    // The one file a user cannot skip: it defines the wrapper function and
    // exports the JLO_HOME the rest of the layout hangs off. A failure here
    // means the printed instructions would point at nothing, so it is fatal
    // where the two optional stubs are warnings.
    write_atomic(&layout.home.join("jlo.sh"), jlo_sh(layout).as_bytes())
        .context("could not write jlo.sh; J'Lo cannot be loaded from your shell profile.")?;

    let mut partial = false;
    if let Err(e) = write_atomic(
        &layout.home.join("autoload.sh"),
        autoload_sh(layout).as_bytes(),
    ) {
        ui::warning!("{e:#} cd autoloading is unavailable.");
        partial = true;
    }
    if let Err(e) = write_atomic(
        &layout.home.join("completions.sh"),
        completions_sh(layout).as_bytes(),
    ) {
        ui::warning!("{e:#} Tab completion is unavailable.");
        partial = true;
    }
    if partial {
        hint_at_the_repair();
    }
    Ok(())
}

/// The one recovery line, printed wherever something optional did not land.
/// Shared so the completion scripts and the stubs cannot drift into saying it
/// differently, or one of them into not saying it at all.
fn hint_at_the_repair() {
    ui::hint!("Re-run the installer once that path is writable to restore it.");
}

/// Completion scripts, generated from this binary's own clap tree.
///
/// Written at install time rather than loaded via `source <(jlo completions
/// bash)` so that shell startup costs no subprocess. A failure is a
/// convenience lost, not a broken install.
fn write_completions(layout: &Layout) {
    if let Err(e) = fs::create_dir_all(&layout.completions) {
        ui::warning!(
            "could not create {:?}: {e}. Shell completions are unavailable.",
            layout.completions
        );
        hint_at_the_repair();
        return;
    }
    let mut partial = false;
    for (shell, name) in [
        (clap_complete::Shell::Bash, "jlo.bash"),
        (clap_complete::Shell::Zsh, "_jlo"),
    ] {
        let script = crate::cli::completion_script(shell);
        if let Err(e) = write_atomic(&layout.completions.join(name), &script) {
            ui::warning!("{e:#} {shell} completions are unavailable.");
            partial = true;
        }
    }
    if partial {
        hint_at_the_repair();
    }
}

// ---------------------------------------------------------------------------
// Generated stubs
// ---------------------------------------------------------------------------

fn jlo_sh(layout: &Layout) -> String {
    format!(
        "{GENERATED_HEADER}\
# Source this from your shell profile. The line never changes: an upgrade
# regenerates the files it points at.
export JLO_HOME={home}
{DIALECT_DISPATCH}\
if [ -n \"$_jlo_d\" ] && [ -s \"$JLO_HOME/bin/jlo-init.$_jlo_d\" ]; then
  . \"$JLO_HOME/bin/jlo-init.$_jlo_d\"
fi
unset _jlo_d
",
        home = sq(&display(&layout.home))
    )
}

fn autoload_sh(layout: &Layout) -> String {
    // The wrapper path is baked in rather than read from $JLO_HOME: this file
    // is opt-in and may be sourced on its own, by a profile that never ran
    // jlo.sh - and under `set -u` an unset $JLO_HOME would abort it.
    //
    // Guarded on the 'jlo' *function* rather than on the directory, because
    // that is what jlo_after_cd calls: sourcing this without jlo.sh has to be
    // inert, not a stream of errors on every cd. `typeset -f` needs no
    // subshell, and under a shell that lacks it the guard fails closed - which
    // is the right answer there anyway.
    format!(
        "{GENERATED_HEADER}\
# Optional: switches JDK on cd when a .jlorc is in scope. Source after jlo.sh.
{DIALECT_DISPATCH}\
if [ -n \"$_jlo_d\" ]; then
  _jlo_f={prefix}\"$_jlo_d\"
  if typeset -f jlo >/dev/null 2>&1 && [ -s \"$_jlo_f\" ]; then
    . \"$_jlo_f\"
    {AUTOLOAD_MARKER}=1
  fi
  unset _jlo_f
fi
unset _jlo_d
",
        prefix = sq(&display(&layout.bin.join("jlo-autoload.")))
    )
}

fn completions_sh(layout: &Layout) -> String {
    // The zsh half is wrapped in `eval` so this file still parses under a
    // POSIX sh: `(( ... ))` and an array assignment are syntax errors there,
    // and a profile that sources this unconditionally would die on the parse
    // before the dialect test ever ran.
    //
    // zsh autoloads from $fpath, so the directory goes there and `_jlo` is
    // read on the first Tab press rather than in every shell. bash has no
    // equivalent - `complete -F` needs the function to exist - so its half
    // stays eager.
    format!(
        "{GENERATED_HEADER}\
# Optional: tab completion for the 'jlo' command. Source after jlo.sh.
{DIALECT_DISPATCH}\
if [ \"$_jlo_d\" = bash ] && [ -s {comp_bash} ]; then
  . {comp_bash}
  {COMPLETIONS_MARKER}=1
fi
if [ \"$_jlo_d\" = zsh ] && [ -s {comp_zsh} ]; then
  _jlo_comp_dir={comp_dir}
  eval '
    # Must come before compinit: compinit scans $fpath once, so a user whose
    # framework (oh-my-zsh and friends) already ran it gets nothing from this
    # line alone - hence the elif below.
    fpath=(\"$_jlo_comp_dir\" $fpath)
    if (( ! $+functions[compdef] )); then
      autoload -Uz compinit && compinit -i
    elif (( ! $+functions[_jlo] )); then
      # compinit already ran, so register after the fact. The autoload is not
      # optional: \"compdef _jlo jlo\" on its own records the mapping without
      # making _jlo loadable, and completion comes up silently empty.
      autoload -Uz _jlo && compdef _jlo jlo
    fi
  '
  unset _jlo_comp_dir
  {COMPLETIONS_MARKER}=1
fi
unset _jlo_d
",
        comp_bash = sq(&display(&layout.completions.join("jlo.bash"))),
        comp_zsh = sq(&display(&layout.completions.join("_jlo"))),
        comp_dir = sq(&display(&layout.completions)),
    )
}

// ---------------------------------------------------------------------------
// Symlink
// ---------------------------------------------------------------------------

/// Expose a real `jlo` on PATH for non-interactive shells (CI, scripts,
/// agents). The interactive shell function still shadows it and keeps handling
/// `env`/`use`, which must mutate the current shell.
///
/// An optional convenience, so any failure is a warning. We only ever create or
/// refresh a symlink that already points at our own binary; an unrelated file,
/// directory or symlink at that path is left untouched.
#[cfg(unix)]
fn ensure_symlink(layout: &Layout) -> Option<PathBuf> {
    let local_bin = std::env::home_dir()?.join(".local").join("bin");
    let link = local_bin.join("jlo");
    let target = layout.binary();

    if link.symlink_metadata().is_ok() {
        // Already ours and already right: leave it alone. Not merely an
        // optimisation - removing and recreating a correct link opens a window
        // in which 'jlo' is missing from PATH, and one in which something else
        // can take the name between the two syscalls.
        if fs::read_link(&link).is_ok_and(|dest| dest == target) {
            return Some(link);
        }
        // The hint is a command the user pastes, so its paths need shell
        // quoting rather than the Debug quoting the rest of our diagnostics
        // use: a '$' or a backtick in the path would otherwise be expanded.
        ui::warning!("{link:?} already exists and is not managed by J'Lo; leaving it untouched.");
        ui::hint!(
            "To put 'jlo' on PATH yourself: ln -s {} {}",
            sq(&display(&target)),
            sq(&display(&link))
        );
        return None;
    }

    if let Err(e) =
        fs::create_dir_all(&local_bin).and_then(|()| std::os::unix::fs::symlink(&target, &link))
    {
        ui::warning!(
            "could not create {link:?}: {e}. 'jlo' may not be available in non-interactive shells."
        );
        return None;
    }
    Some(link)
}

#[cfg(not(unix))]
fn ensure_symlink(_layout: &Layout) -> Option<PathBuf> {
    None
}

// ---------------------------------------------------------------------------
// Receipt
// ---------------------------------------------------------------------------

/// `None` for both a missing and a malformed receipt.
///
/// The two are distinguished where it matters - `selfupdate` stops on a
/// malformed one rather than guessing - but neither is a reason for an
/// ordinary command to refuse to run.
/// The reading `selfupdate` needs, where the two failures are *not* the same
/// thing: a missing receipt is an install that predates them and may be
/// updated, a malformed one is an error that stops the update and names the
/// file, because guessing is how a package-manager install gets clobbered.
pub(crate) fn load_receipt(layout: &Layout) -> Result<Option<Receipt>> {
    let path = layout.receipt();
    let raw = match fs::read_to_string(&path) {
        Ok(raw) => raw,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(e) => return Err(anyhow!("could not read {path:?}: {e}.")),
    };
    serde_json::from_str(&raw)
        .map(Some)
        .map_err(|e| anyhow!("{path:?} is not a valid install receipt: {e}."))
}

fn read_receipt(layout: &Layout) -> Option<Receipt> {
    let raw = fs::read_to_string(layout.receipt()).ok()?;
    serde_json::from_str(&raw).ok()
}

fn write_receipt(layout: &Layout, method: &str, symlink: Option<&Path>) -> Result<()> {
    let receipt = Receipt {
        version: VERSION.to_string(),
        method: method.to_string(),
        jlo_home: display(&layout.home),
        binary: display(&layout.binary()),
        symlink: symlink.map(display),
    };
    let mut json = serde_json::to_string_pretty(&receipt)
        .context("could not serialise the install receipt")?;
    json.push('\n');
    write_atomic(&layout.receipt(), json.as_bytes())
}

// ---------------------------------------------------------------------------
// Self-healing
// ---------------------------------------------------------------------------

/// Rewrite the generated files when the receipt disagrees with this binary.
///
/// That disagreement is the known-incomplete state: the binary landed, the
/// scripts or the receipt did not. Rather than report it and hand the user a
/// `--repair` command to type, any invocation clears it - a few idempotent
/// writes, no network.
///
/// Three guards keep this from running where it would be wrong. A missing
/// receipt is an install that predates them, not a broken one. A receipt
/// naming a *different* binary means this executable is not the install it
/// describes - a build in `target/release`, say. And a receipt describing a
/// *different* `$JLO_HOME` than the one we resolved means the two do not
/// belong together however the binary path lines up, so a copied install
/// cannot rewrite the original's scripts.
pub(crate) fn self_heal() {
    let Ok(home) = crate::jlo_home_dir() else {
        return;
    };
    let layout = Layout::new(home);
    let Some(receipt) = read_receipt(&layout) else {
        return;
    };
    if receipt.version == VERSION {
        return;
    }
    if !same_path(Path::new(&receipt.jlo_home), &layout.home) {
        return;
    }
    if !is_current_exe(Path::new(&receipt.binary)) {
        return;
    }

    // Somebody else is publishing. They will leave a consistent layout behind,
    // so there is nothing here worth waiting - or racing - for.
    let Ok(Some(_lock)) = Lock::try_acquire(&layout.home) else {
        return;
    };

    if let Err(e) = write_layout(&layout).and_then(|()| {
        write_receipt(
            &layout,
            &receipt.method,
            receipt.symlink.as_deref().map(Path::new),
        )
    }) {
        ui::warning!("could not refresh the generated shell files: {e:#}");
        ui::hint!("Re-run the installer to repair this install.");
    }
}

pub(crate) fn is_current_exe(path: &Path) -> bool {
    let Ok(exe) = std::env::current_exe() else {
        return false;
    };
    same_path(&exe, path)
}

/// Compares resolved paths where both exist: `$JLO_HOME` may itself be reached
/// through a symlink, and the receipt records whatever spelling it was given.
pub(crate) fn same_path(a: &Path, b: &Path) -> bool {
    match (a.canonicalize(), b.canonicalize()) {
        (Ok(a), Ok(b)) => a == b,
        _ => a == b,
    }
}

// ---------------------------------------------------------------------------
// Reporting
// ---------------------------------------------------------------------------

/// What the installer prints. Runnable commands, not prose to act on: one line
/// makes jlo permanent, the next makes it effective in the shell the user is
/// sitting in.
///
/// The installer cannot do that second part itself - it runs in a subshell
/// under `curl | bash` and cannot mutate its parent (ADR-0001, the same reason
/// `jlo env` exists at all). That the *user* runs it is what keeps this
/// non-invasive rather than merely convenient: nothing writes to their profile
/// but them.
///
/// Everything here goes to stderr. stdout is the environment channel, and from
/// 0.4.0 `selfupdate` prints a `. jlo.sh` line there for the wrapper to eval.
fn report(layout: &Layout, had_receipt: bool, symlink: Option<&Path>) {
    let home_dir = std::env::home_dir();
    let profile = home_dir.as_deref().map(login_shell_profile);
    let activated = profile.as_deref().is_some_and(profile_sources_jlo);

    ui::created!(
        "J'Lo {VERSION} installed to {}.",
        tilde(&layout.home, home_dir.as_deref())
    );

    if had_receipt && activated {
        path_nudge(symlink);
        return;
    }

    let Some(profile) = profile else {
        // No home directory: there is no profile to name and no portable line
        // to print. The absolute paths in the layout still work.
        ui::hint!(
            "Source {:?} from your shell profile.",
            layout.home.join("jlo.sh")
        );
        return;
    };
    let target = profile_target(&profile, home_dir.as_deref());

    if had_receipt {
        eprintln!();
        ui::warning!(
            "{} does not source jlo.sh - it looks like the line below was never added.",
            tilde(&profile, home_dir.as_deref())
        );
    }

    let main = snippet(layout, home_dir.as_deref(), "jlo.sh");
    eprintln!("\nTo activate — run both lines:\n");
    eprintln!("    {}", append_command(&main, &target));
    eprintln!("    . {main}");
    eprintln!("\nOptional — switch JDK on cd, and tab completion:\n");
    for name in ["autoload.sh", "completions.sh"] {
        let path = snippet(layout, home_dir.as_deref(), name);
        eprintln!("    {}", append_command(&path, &target));
    }
    eprintln!("\nThese lines never change: upgrades regenerate the files they point at.");
    path_nudge(symlink);
}

/// Only nudge about PATH when the symlink was actually created and
/// `~/.local/bin` is not already on PATH - usually the case on macOS, rarely
/// on Linux.
fn path_nudge(symlink: Option<&Path>) {
    let Some(link) = symlink else { return };
    let Some(dir) = link.parent() else { return };
    let on_path = std::env::var_os("PATH")
        .is_some_and(|path| std::env::split_paths(&path).any(|entry| entry == dir));
    if on_path {
        return;
    }
    eprintln!(
        "\nAlso add {} to your PATH so 'jlo' works in non-interactive shells\n\
         (CI, scripts, AI agents) and for 'jlo home':\n\n    \
         export PATH=\"$HOME/.local/bin:$PATH\"",
        tilde(dir, std::env::home_dir().as_deref())
    );
}

/// The profile the *login* shell reads.
///
/// `$SHELL` is the right signal here - unlike in the dialect dispatch, where
/// the *running* shell is what matters and `$SHELL` would be wrong. The trap
/// is bash: macOS's Terminal.app starts login shells, which read
/// `.bash_profile` and never `.bashrc`.
///
/// A wrong guess is harmless by construction: the path stays visible in the
/// printed command, so correcting it is a one-word edit rather than a line
/// silently appended to the wrong file.
fn login_shell_profile(home: &Path) -> PathBuf {
    let shell = std::env::var("SHELL").unwrap_or_default();
    let name = Path::new(&shell)
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();
    match name.as_str() {
        "zsh" => home.join(".zshrc"),
        "bash" if cfg!(target_os = "macos") => home.join(".bash_profile"),
        "bash" => home.join(".bashrc"),
        // Neither, or no $SHELL at all: ~/.profile is what a POSIX login shell
        // reads.
        _ => home.join(".profile"),
    }
}

/// Fail open: an unreadable or missing profile counts as "not activated", so
/// the worst case is a duplicated line rather than a silent non-install.
///
/// Commented-out mentions do not count, whether the `#` opens the line or
/// trails a command on it. That is not pedantry: the line the installer prints
/// is exactly the one a user comments out to turn J'Lo off, and counting it is
/// the one way this check can fail *closed* - withholding the instructions
/// from someone whose shell is not in fact set up.
///
/// The comment stripping is deliberately crude - a `#` at the start of a line
/// or after whitespace - rather than a shell tokeniser. It errs toward
/// stripping too much, which is the harmless direction: over-stripping shows
/// the instructions to someone who did not need them, and the same is true of
/// the other way this can be wrong, a line that lives in `~/.zprofile` or in a
/// file sourced from the candidate. Both cost one duplicated line.
fn profile_sources_jlo(profile: &Path) -> bool {
    fs::read_to_string(profile).is_ok_and(|body| {
        body.lines().any(|line| {
            let code = match line
                .char_indices()
                .find(|&(i, c)| c == '#' && (i == 0 || line[..i].ends_with(char::is_whitespace)))
            {
                Some((i, _)) => &line[..i],
                None => line,
            };
            code.contains("jlo.sh")
        })
    })
}

// ---------------------------------------------------------------------------
// Rendering helpers
// ---------------------------------------------------------------------------

/// A default install prints the unexpanded `"$HOME/.jlo/..."` so the same line
/// works on another machine; the generated files it points at hold the real
/// paths. A custom `JLO_HOME` is quoted like any other baked path, so a `$` in
/// it stays a `$`.
fn snippet(layout: &Layout, home: Option<&Path>, name: &str) -> String {
    if home.is_some_and(|h| layout.home == h.join(crate::JLO_HOME_DIR_NAME)) {
        format!("\"$HOME/{}/{name}\"", crate::JLO_HOME_DIR_NAME)
    } else {
        sq(&display(&layout.home.join(name)))
    }
}

fn source_line(path: &str) -> String {
    format!("[ -s {path} ] && . {path}")
}

/// The command that appends one line to the user's profile.
///
/// `printf '%s\n'` rather than `echo`, which is the one place the Homebrew
/// output this is modelled on would go wrong for us: `echo` expands backslash
/// escapes in zsh, in dash, and in any bash built with `xpg_echo`. Homebrew's
/// payload is a fixed string; ours carries a path the user chose, so a
/// backslash in a custom `JLO_HOME` would be rewritten - `\n` splitting the
/// profile line in half - on its way into the file. `printf` with a literal
/// format string has no such reading.
fn append_command(snippet: &str, target: &str) -> String {
    format!("printf '%s\\n' {} >> {target}", sq(&source_line(snippet)))
}

/// The `>>` target. `~` is left unquoted so the shell expands it; a `$HOME`
/// with anything unusual in it falls back to a quoted absolute path, which is
/// less readable but correct.
fn profile_target(profile: &Path, home: Option<&Path>) -> String {
    let simple = |rest: &str| {
        !rest.is_empty()
            && rest
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-' | '/'))
    };
    if let Some(rest) = home.and_then(|h| profile.strip_prefix(h).ok()) {
        let rest = display(rest);
        if simple(&rest) {
            return format!("~/{rest}");
        }
    }
    sq(&display(profile))
}

/// `~/x` for human-readable prose. Never used where a shell will read it back.
fn tilde(path: &Path, home: Option<&Path>) -> String {
    match home.and_then(|h| path.strip_prefix(h).ok()) {
        Some(rest) => format!("~/{}", display(rest)),
        None => display(path),
    }
}

/// POSIX single-quoting. An apostrophe closes the quote, so it is emitted as
/// the standard escape - close, escaped apostrophe, reopen.
fn sq(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

fn display(path: &Path) -> String {
    path.to_string_lossy().into_owned()
}

/// Write `contents` to `path` via a temp file **in `path`'s own directory**.
///
/// `rename` is only atomic within one filesystem, so the staging file cannot
/// live in `std::env::temp_dir()`; a sibling is the only placement that holds
/// when `bin/` is itself a mount point or a symlink. Without this an
/// interruption leaves a *truncated* script, which is worse than a stale one.
fn write_atomic(path: &Path, contents: &[u8]) -> Result<()> {
    let dir = path
        .parent()
        .ok_or_else(|| anyhow!("{path:?} has no parent directory."))?;
    let name = path
        .file_name()
        .ok_or_else(|| anyhow!("{path:?} has no file name."))?
        .to_string_lossy()
        .into_owned();
    let tmp = dir.join(format!(".{name}.tmp{}", std::process::id()));

    let staged = fs::File::create(&tmp).and_then(|mut f| {
        f.write_all(contents)?;
        f.sync_all()
    });
    if let Err(e) = staged {
        let _ = fs::remove_file(&tmp);
        return Err(anyhow!("could not write {path:?}: {e}."));
    }
    if let Err(e) = fs::rename(&tmp, path) {
        let _ = fs::remove_file(&tmp);
        return Err(anyhow!("could not write {path:?}: {e}."));
    }
    sync_dir(dir);
    Ok(())
}

/// Make a `rename` durable by flushing the *directory entry*, not just the
/// file's contents.
///
/// Without it the ordering this module relies on is not a crash guarantee at
/// all: the receipt is the commit marker, and a crash could leave it on disk
/// while the script it vouches for is still only in the page cache. Best
/// effort, because some filesystems refuse an `fsync` on a directory and that
/// is not a reason to fail an install that otherwise succeeded.
pub(crate) fn sync_dir(dir: &Path) {
    if let Ok(handle) = fs::File::open(dir) {
        let _ = handle.sync_all();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn layout_at(home: &Path) -> Layout {
        Layout::new(home.to_path_buf())
    }

    #[test]
    fn single_quoting_survives_an_apostrophe() {
        assert_eq!(sq("o'brien"), r"'o'\''brien'");
        assert_eq!(sq("$x `id`"), "'$x `id`'");
    }

    #[test]
    fn a_default_home_keeps_the_snippet_portable() {
        let home = Path::new("/home/u");
        let layout = layout_at(&home.join(".jlo"));
        assert_eq!(
            snippet(&layout, Some(home), "jlo.sh"),
            "\"$HOME/.jlo/jlo.sh\""
        );
    }

    #[test]
    fn a_custom_home_is_spelled_out_and_quoted() {
        let home = Path::new("/home/u");
        let layout = layout_at(Path::new("/opt/jlo"));
        assert_eq!(snippet(&layout, Some(home), "jlo.sh"), "'/opt/jlo/jlo.sh'");
    }

    #[test]
    fn profile_target_uses_tilde_for_a_plain_path() {
        let home = Path::new("/home/u");
        assert_eq!(profile_target(&home.join(".zshrc"), Some(home)), "~/.zshrc");
    }

    /// `~` is the shell's own expansion of `$HOME`, so an apostrophe in the
    /// home directory is not the printed line's problem - it stays readable,
    /// and correct, exactly where a baked absolute path would need escaping.
    #[test]
    fn profile_target_keeps_the_tilde_over_an_unusual_home() {
        let home = Path::new("/home/o'brien");
        assert_eq!(profile_target(&home.join(".zshrc"), Some(home)), "~/.zshrc");
    }

    /// What the quoting is actually for: a name `~/` cannot stand in for.
    #[test]
    fn profile_target_quotes_a_name_the_tilde_cannot_carry() {
        let home = Path::new("/home/u");
        let odd = home.join("my profile").join(".zshrc");
        assert_eq!(
            profile_target(&odd, Some(home)),
            "'/home/u/my profile/.zshrc'"
        );
        assert_eq!(
            profile_target(Path::new("/etc/zshrc"), Some(home)),
            "'/etc/zshrc'"
        );
    }

    #[test]
    fn write_atomic_leaves_no_temp_file_behind() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("jlo.sh");
        write_atomic(&path, b"hello\n").expect("write");
        assert_eq!(fs::read_to_string(&path).expect("read"), "hello\n");
        let leftovers: Vec<_> = fs::read_dir(dir.path())
            .expect("read_dir")
            .filter_map(Result::ok)
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n != "jlo.sh")
            .collect();
        assert!(
            leftovers.is_empty(),
            "temp files left behind: {leftovers:?}"
        );
    }

    #[test]
    fn a_receipt_round_trips() {
        let dir = tempfile::tempdir().expect("tempdir");
        let layout = layout_at(dir.path());
        write_receipt(
            &layout,
            "installer",
            Some(Path::new("/home/u/.local/bin/jlo")),
        )
        .expect("write receipt");
        let back = read_receipt(&layout).expect("receipt");
        assert_eq!(back.version, VERSION);
        assert_eq!(back.method, "installer");
        assert_eq!(back.symlink.as_deref(), Some("/home/u/.local/bin/jlo"));
    }

    #[test]
    fn a_malformed_receipt_reads_as_absent() {
        let dir = tempfile::tempdir().expect("tempdir");
        let layout = layout_at(dir.path());
        fs::write(layout.receipt(), "{ not json").expect("write");
        assert!(read_receipt(&layout).is_none());
    }
}
