//! The hidden install verb: writes jlo's layout under `$JLO_HOME`.
//!
//! The shell code is compiled in from `shell/` with `include_str!`, so there
//! is one artifact to verify and the files on disk always match the binary
//! that wrote them.
//!
//! Intercepted from raw argv before `Cli::parse()`: `hide = true` would still
//! leak it into generated completions and "did you mean" suggestions.
//!
//! Every file goes down as a temp file plus a `rename` *in its own
//! directory*, so an interruption leaves a stale script, never a truncated one.

use crate::CommandError;
use crate::store::same_path;
use crate::ui;
use crate::ui::tilde;
use anyhow::{Context, Result, anyhow};
use std::fs::{self, File};
use std::io::Write as _;
use std::path::{Path, PathBuf};

/// Not part of the CLI contract: only the installers call it.
pub(crate) const VERB: &str = "__install";

/// The installers give the staged file this name too, so the staging cleanup
/// knows exactly which file was its own.
const BINARY_NAME: &str = "jlo-bin";

/// The installers' staging directory beside the binary. Matched as a prefix:
/// the pid in the real name is whoever staged it, usually a shell, not us.
const STAGING_PREFIX: &str = ".jlo-install";

const VERSION: &str = env!("CARGO_PKG_VERSION");

// Verbatim, no interpolation, which keeps them shellcheck-able files rather
// than templates. Only the entry files are generated.
const INIT: &str = include_str!("../shell/jlo-init.sh");
const AUTOLOAD: &str = include_str!("../shell/jlo-autoload.sh");
const COMPLETIONS_ZSH: &str = include_str!("../shell/jlo-completions.zsh");

/// The implementation files under `bin/`, as the entry files name them.
const INIT_FILE: &str = "jlo-init.sh";
const AUTOLOAD_FILE: &str = "jlo-autoload.sh";
const COMPLETIONS_ZSH_FILE: &str = "jlo-completions.zsh";

/// The shell dialect files 0.4.0 and 0.5.0 wrote under `bin/`, which their
/// stubs sourced and nothing sources any more.
const RETIRED_DIALECTS: [&str; 4] = [
    "jlo-init.bash",
    "jlo-init.zsh",
    "jlo-autoload.bash",
    "jlo-autoload.zsh",
];

/// The first line of every file in [`RETIRED_DIALECTS`], as those releases
/// wrote it.
const RETIRED_DIALECT_HEADER: &str =
    "# Generated by J'Lo - do not edit. Rewritten on every install and update.\n";

/// The install receipt 0.4.0 and 0.5.0 wrote, which nothing reads any more.
const RETIRED_RECEIPT: &str = "install-receipt.json";

const GENERATED_HEADER: &str = "\
# Generated by J'Lo - edits are lost on the next install or 'jlo selfupdate'.
";

/// Set once the optional file has loaded; [`print_reload`] re-sources only
/// what they mark. Deliberately not exported: they answer "did *this* shell
/// opt in?", and an exported one would leak into every child.
const AUTOLOAD_MARKER: &str = "_JLO_AUTOLOAD";
const COMPLETIONS_MARKER: &str = "_JLO_COMPLETIONS";

/// A file the user's profile sources. The names are the install contract: the
/// lines a user pasted name them, so they never change.
#[derive(Debug)]
struct Entry {
    name: &'static str,
    /// The variable an opt-in entry sets once loaded; `None` for the required
    /// one, which every reload sources.
    marker: Option<&'static str>,
}

const JLO_SH: Entry = Entry {
    name: "jlo.sh",
    marker: None,
};
const AUTOLOAD_SH: Entry = Entry {
    name: "autoload.sh",
    marker: Some(AUTOLOAD_MARKER),
};
const COMPLETIONS_SH: Entry = Entry {
    name: "completions.sh",
    marker: Some(COMPLETIONS_MARKER),
};

/// In the order the activation text lists them.
const ENTRIES: [&Entry; 3] = [&JLO_SH, &AUTOLOAD_SH, &COMPLETIONS_SH];

/// The directories and files J'Lo owns under `$JLO_HOME`.
#[derive(Debug)]
pub(crate) struct Layout {
    home: PathBuf,
    bin: PathBuf,
    binary: PathBuf,
    completions: PathBuf,
}

impl Layout {
    pub(crate) fn curl(home: PathBuf) -> Self {
        let bin = home.join("bin");
        Self {
            binary: bin.join(BINARY_NAME),
            bin,
            completions: home.join("completions"),
            home,
        }
    }

    pub(crate) fn home(&self) -> &Path {
        &self.home
    }

    fn bin_dir(&self) -> &Path {
        &self.bin
    }

    fn entry(&self, entry: &Entry) -> PathBuf {
        self.home.join(entry.name)
    }

    fn implementation(&self, name: &str) -> PathBuf {
        self.bin.join(name)
    }

    /// Remove staging directories an earlier run abandoned, sparing `keep`.
    fn sweep_stale_staging(&self, keep: Option<&Path>) {
        crate::store::sweep_stale_staging(&self.bin, STAGING_PREFIX, keep);
    }

    /// Also the symlink target. The name is load-bearing: `~/.local/bin/jlo`
    /// is only refreshed when it already points at exactly this path, so a
    /// rename would leave every existing symlink dangling.
    pub(crate) fn binary(&self) -> &Path {
        &self.binary
    }
}

/// `args` is the raw argv *after* the verb token.
pub(crate) fn cmd_install(args: &[String]) -> Result<(), CommandError> {
    let layout = Layout::curl(crate::home::jlo_home_dir()?);
    // Armed before the options are read: the installer that `exec`d us has no
    // line left to run, so even a rejected option is the last chance to clear
    // the directory we came out of.
    let staging = Staging::around(&layout, args.iter().any(|arg| arg == "--publish-self"));
    let mut publish_self = false;
    for arg in args {
        match arg.as_str() {
            "--publish-self" => publish_self = true,
            other => return Err(anyhow!("unknown option {other:?} for {VERB}").into()),
        }
    }
    // Every run has a new pid, so nothing else ever comes back for an
    // abandoned staging directory.
    layout.sweep_stale_staging(staging.dir());
    // Read before writing: a first install gets the activation block, a
    // reinstall one line.
    let reinstall = layout.entry(&JLO_SH).exists();

    if publish_self {
        // Nothing under `$JLO_HOME` has been written yet.
        publish_binary(&layout).map_err(|e| {
            CommandError::with_hint(
                e,
                "J'Lo was not changed; any existing install is still in place.",
            )
        })?;
    }
    let stubs_replaced = write_layout(&layout)?;
    remove_retired(&layout, stubs_replaced);
    let symlink = ensure_symlink(&layout);

    report(&layout, reinstall, symlink.as_deref());
    Ok(())
}

/// Remove what earlier releases wrote and nothing reads any more - only a file
/// whose contents prove J'Lo wrote it, since `$JLO_HOME` may hold the user's
/// own files. The empty `.selfupdate.lock` proves nothing, so it stays.
///
/// The dialect files go only once every stub has been replaced: a stub this
/// run could not rewrite is an old one, and still sources them.
fn remove_retired(layout: &Layout, stubs_replaced: bool) {
    let mut ours = Vec::new();
    let receipt = layout.home.join(RETIRED_RECEIPT);
    if fs::read_to_string(&receipt).is_ok_and(|text| is_retired_receipt(&text)) {
        ours.push(receipt);
    }
    if stubs_replaced {
        for name in RETIRED_DIALECTS {
            let path = layout.bin.join(name);
            if fs::read_to_string(&path).is_ok_and(|text| text.starts_with(RETIRED_DIALECT_HEADER))
            {
                ours.push(path);
            }
        }
    }
    for path in ours {
        if let Err(e) = fs::remove_file(&path) {
            ui::warning!("could not remove {path:?}, which J'Lo no longer uses: {e}");
        }
    }
}

/// Whether `text` is the pretty-printed receipt 0.4.0 and 0.5.0 wrote: its
/// keys, in their order, one per line, and an optional `symlink` last.
fn is_retired_receipt(text: &str) -> bool {
    let mut lines = text.lines();
    if lines.next() != Some("{") {
        return false;
    }
    for key in ["version", "method", "jlo_home", "binary"] {
        if !lines
            .next()
            .is_some_and(|line| line.starts_with(&format!("  \"{key}\": \"")))
        {
            return false;
        }
    }
    let mut rest = lines.next();
    if rest.is_some_and(|line| line.starts_with("  \"symlink\": \"")) {
        rest = lines.next();
    }
    rest == Some("}") && lines.next().is_none()
}

/// Move the running executable to its published path.
///
/// The installers run the staged binary, so `bin/jlo-bin` is replaced only
/// once the new one has proved it can start (and an installer overwriting a
/// running binary would hit `ETXTBSY` on Linux). Staged beside the
/// destination because `rename` fails across filesystems.
///
/// The process keeps its inode across the rename, so it *is* the published
/// binary from here on and may write the layout from its own templates.
fn publish_binary(layout: &Layout) -> Result<()> {
    let exe = std::env::current_exe().context("could not find the running J'Lo binary")?;
    let target = layout.binary();
    if same_path(&exe, target) {
        return Ok(());
    }

    fs::create_dir_all(layout.bin_dir())
        .with_context(|| format!("could not create {:?}", layout.bin_dir()))?;
    // The contents first: `tar` and `cp` did not flush them, and a crash after
    // the rename could otherwise leave a durable entry in front of a binary
    // still only in the page cache.
    File::open(&exe)
        .and_then(|handle| handle.sync_all())
        .with_context(|| format!("could not flush {exe:?} to disk"))?;
    fs::rename(&exe, target).with_context(|| format!("could not publish {exe:?} to {target:?}"))?;
    // Durable before the layout written next vouches for it.
    sync_dir(layout.bin_dir());

    Ok(())
}

pub(crate) fn is_current_exe(path: &Path) -> bool {
    let Ok(exe) = std::env::current_exe() else {
        return false;
    };
    same_path(&exe, path)
}

/// The installer's staging directory, cleared when this value is dropped.
/// `install.sh` `exec`s the staged binary, so only it can still tidy up.
///
/// Removes the staged file, then the directory *only if that emptied it*.
/// Never recursive: the path derives from `current_exe()`, and a wrong answer
/// there must cost nothing that belongs to somebody else.
#[derive(Debug)]
struct Staging(Option<PathBuf>);

impl Staging {
    /// `None` unless this executable is demonstrably a staged one: publishing
    /// was asked for, it is not already the published binary, and its
    /// directory is a child of *this* install's `bin/` - the name alone would
    /// match any `.jlo-install*` directory anywhere.
    fn around(layout: &Layout, publish_self: bool) -> Self {
        if !publish_self {
            return Self(None);
        }
        let Ok(exe) = std::env::current_exe() else {
            return Self(None);
        };
        if same_path(&exe, layout.binary()) {
            return Self(None);
        }
        let dir = exe.parent().filter(|dir| {
            dir.file_name()
                .is_some_and(|name| name.to_string_lossy().starts_with(STAGING_PREFIX))
                && dir
                    .parent()
                    .is_some_and(|up| same_path(up, layout.bin_dir()))
        });
        Self(dir.map(Path::to_path_buf))
    }

    fn dir(&self) -> Option<&Path> {
        self.0.as_deref()
    }
}

impl Drop for Staging {
    fn drop(&mut self) {
        let Some(dir) = self.0.take() else {
            return;
        };
        // Gone already on the happy path: publishing renamed it out.
        let _ = fs::remove_file(dir.join(BINARY_NAME));
        // Not `remove_dir_all`. Anything still in here was not put there by
        // this run, and keeping it costs an empty directory at worst.
        let _ = fs::remove_dir(&dir);
    }
}

/// Shell code on stdout for the calling shell to `eval`, so the shell that ran
/// `jlo selfupdate` loads the freshly written wrapper. Re-sources only the
/// optional files this shell had *already* loaded, by their markers.
///
/// Every optional line is a full `if`, not `[ ... ] && . ...`: a false
/// `[ -n ... ]` would fail the `&&`-joined payload and turn a successful
/// update into a non-zero `jlo selfupdate`.
pub(crate) fn print_reload(layout: &Layout, wrapped: bool) -> Result<()> {
    let lines: Vec<String> = ENTRIES
        .iter()
        .map(|entry| {
            let path = sq(&display(&layout.entry(entry)));
            match entry.marker {
                None => format!(". {path}"),
                Some(marker) => format!("if [ -n \"${{{marker}-}}\" ]; then . {path}; fi"),
            }
        })
        .collect();
    crate::shellenv::emit(&lines, wrapped)
}

/// Everything under `$JLO_HOME` except the binary and the symlink. The
/// optional files warn rather than fail: a convenience lost is not a broken
/// install.
///
/// Answers whether every stub was replaced; an optional one that was not may
/// still be an earlier release's.
fn write_layout(layout: &Layout) -> Result<bool> {
    fs::create_dir_all(&layout.bin)
        .with_context(|| format!("could not create {:?}", layout.bin))?;

    // The wrappers first: the stubs below are what point at them.
    for (name, body) in [
        (INIT_FILE, INIT),
        (AUTOLOAD_FILE, AUTOLOAD),
        (COMPLETIONS_ZSH_FILE, COMPLETIONS_ZSH),
    ] {
        write_atomic(&layout.implementation(name), body.as_bytes())?;
    }

    let completions_partial = write_completions(layout);
    let mut stubs_replaced = true;

    // The one required file: without it the printed instructions point at
    // nothing, so it is fatal where the optional stubs warn.
    let jlo_sh = init_stub(
        layout,
        "\
# Source this from your shell profile. The line never changes: an upgrade
# regenerates the files it points at.
",
    );
    write_atomic(&layout.entry(&JLO_SH), jlo_sh.as_bytes())
        .context("could not write jlo.sh; J'Lo cannot be loaded from your shell profile.")?;

    let autoload_sh = autoload_stub(
        layout,
        "\
# Optional: switches JDK on cd when a .jlorc is in scope. Source after jlo.sh.
",
    );
    if let Err(e) = write_atomic(&layout.entry(&AUTOLOAD_SH), autoload_sh.as_bytes()) {
        ui::warning!("{e:#} cd autoloading is unavailable.");
        stubs_replaced = false;
    }
    if let Err(e) = write_atomic(
        &layout.entry(&COMPLETIONS_SH),
        completions_sh(layout).as_bytes(),
    ) {
        ui::warning!("{e:#} Tab completion is unavailable.");
        stubs_replaced = false;
    }
    if completions_partial || !stubs_replaced {
        ui::hint!("Re-run the installer once that path is writable to restore it.");
    }
    Ok(stubs_replaced)
}

/// Everything under `$JLO_HOME` but the binary: what `jlo selfupdate` does
/// when J'Lo is already current, the repair for an upgrade cut off between
/// the binary and its scripts.
pub(crate) fn refresh_layout(layout: &Layout) -> Result<()> {
    write_layout(layout)?;
    ensure_symlink(layout);
    Ok(())
}

/// Completion scripts from this binary's clap tree, written at install time
/// rather than `source <(jlo completions bash)` so shell startup costs no
/// subprocess. `true` when any could not be written.
fn write_completions(layout: &Layout) -> bool {
    if let Err(e) = fs::create_dir_all(&layout.completions) {
        ui::warning!(
            "could not create {:?}: {e}. Shell completions are unavailable.",
            layout.completions
        );
        return true;
    }
    let mut partial = false;
    for (shell, name) in [
        (clap_complete::Shell::Bash, "jlo.bash"),
        (clap_complete::Shell::Zsh, "_jlo"),
    ] {
        let script = crate::cli::completion_script(shell);
        if let Err(e) = write_atomic(&layout.completions.join(name), &script) {
            ui::warning!("{e:#} {shell} completions are unavailable.");
            partial = true;
        }
    }
    partial
}

fn init_stub(layout: &Layout, note: &str) -> String {
    format!(
        "{GENERATED_HEADER}{note}export JLO_HOME={home}\n{load}\n",
        home = sq(&display(&layout.home)),
        load = guarded_source(&format!("\"$JLO_HOME/bin/{INIT_FILE}\""), None),
    )
}

/// Source `path` - a shell word, quoted by the caller - when readable, setting
/// `marker` once it has loaded. A profile sourcing this under `set -e` must not
/// die for a missing or failing target, so a stub's status is always 0 and
/// errexit is off while the target runs: `|| :` and an `if` condition both give
/// that. Not `. f && M=1 || :`, which `ShellCheck` flags (`SC2015`).
fn guarded_source(path: &str, marker: Option<&str>) -> String {
    match marker {
        None => format!("if [ -r {path} ]; then . {path} || :; fi"),
        Some(marker) => format!("if [ -r {path} ] && . {path}; then {marker}=1; fi"),
    }
}

/// The path is baked in rather than read from `$JLO_HOME`: this file may be
/// sourced without `jlo.sh`, and under `set -u` an unset `$JLO_HOME` aborts.
///
/// Guarded on the 'jlo' *function*, which `jlo_after_cd` calls: without
/// `jlo.sh` this must be inert, not an error on every cd. Where `typeset` is
/// missing the guard fails closed.
fn autoload_stub(layout: &Layout, note: &str) -> String {
    format!(
        "{GENERATED_HEADER}{note}\
# shellcheck disable=SC3044
if typeset -f jlo >/dev/null 2>&1; then
  {load}
fi
",
        load = guarded_source(&sq(&display(&layout.implementation(AUTOLOAD_FILE))), None),
    )
}

fn completions_sh(layout: &Layout) -> String {
    // zsh autoloads `_jlo` from $fpath on the first Tab press; bash's
    // `complete -F` needs the function to exist, so its half stays eager.
    //
    // The builtin tests are the spoof guard: an exported ZSH_VERSION reaches a
    // bash child, but `setopt` and `shopt` cannot.
    format!(
        "{GENERATED_HEADER}\
# Optional: tab completion for the 'jlo' command. Source after jlo.sh.
if [ -n \"${{ZSH_VERSION-}}\" ] && command -v setopt >/dev/null 2>&1; then
  if [ -r {comp_zsh} ]; then
    _jlo_comp_dir={comp_dir}
    {load_zsh}
    unset _jlo_comp_dir
  fi
elif [ -n \"${{BASH_VERSION-}}\" ] && command -v shopt >/dev/null 2>&1; then
  {load_bash}
fi
",
        comp_zsh = sq(&display(&layout.completions.join("_jlo"))),
        comp_dir = sq(&display(&layout.completions)),
        load_zsh = guarded_source(
            &sq(&display(&layout.implementation(COMPLETIONS_ZSH_FILE))),
            Some(COMPLETIONS_MARKER)
        ),
        load_bash = guarded_source(
            &sq(&display(&layout.completions.join("jlo.bash"))),
            Some(COMPLETIONS_MARKER)
        ),
    )
}

/// A real `jlo` on PATH for non-interactive shells; the shell function still
/// shadows it interactively. Only a link that already points at our binary is
/// touched; anything else at that path is left alone.
fn ensure_symlink(layout: &Layout) -> Option<PathBuf> {
    let local_bin = std::env::home_dir()?.join(".local").join("bin");
    let link = local_bin.join("jlo");
    let target = layout.binary();

    if link.symlink_metadata().is_ok() {
        // Not merely an optimisation: recreating a correct link opens a window
        // in which 'jlo' is missing, or something else takes the name.
        if fs::read_link(&link).is_ok_and(|dest| dest == target) {
            return Some(link);
        }
        // Shell quoting, not Debug: the user pastes this, and a '$' or a
        // backtick in the path would otherwise be expanded.
        ui::warning!("{link:?} already exists and is not managed by J'Lo; leaving it untouched.");
        ui::hint!(
            "To put 'jlo' on PATH yourself: ln -s {} {}",
            sq(&display(target)),
            sq(&display(&link))
        );
        return None;
    }

    if let Err(e) =
        fs::create_dir_all(&local_bin).and_then(|()| std::os::unix::fs::symlink(target, &link))
    {
        ui::warning!(
            "could not create {link:?}: {e}. 'jlo' may not be available in non-interactive shells."
        );
        return None;
    }
    Some(link)
}

/// The lines that make jlo permanent and effective in this shell, for the
/// user to run: under `curl | bash` the installer cannot change its parent,
/// and nothing writes to the profile but the user.
///
/// The same text whatever the shell and dotfiles: guessing from `$SHELL` risks
/// a file the shell never reads or, for bash, a new login file that switches
/// off the one in use. All stderr: stdout is the environment channel.
fn report(layout: &Layout, reinstall: bool, symlink: Option<&Path>) {
    let home_dir = std::env::home_dir();
    let home = home_dir.as_deref();

    ui::created!("J'Lo {VERSION} installed to {}.", tilde(&layout.home, home));

    // Column 0, not indented: these lines are copied, and terminal selection
    // takes a leading indent with them.
    let main = snippet(layout, home, &JLO_SH);

    // The profile is not read: no text scan can prove a source line runs, and
    // a false "yes" withholds the one line that would fix a broken setup.
    if reinstall {
        eprintln!(
            "\n{}",
            ui::dim("Already in your profile? Nothing to do. Otherwise add:")
        );
        eprintln!("{}", ui::command(&source_line(&main)));
    } else {
        eprintln!(
            "\n{}\n",
            ui::dim("To activate, add these lines to ~/.zshrc or ~/.bashrc:")
        );
        for entry in ENTRIES {
            eprintln!(
                "{}",
                ui::command(&source_line(&snippet(layout, home, entry)))
            );
        }
        // The bash trap: macOS terminals start login shells, which never read
        // `.bashrc`, and read only the first login file that exists - so
        // creating `.bash_profile` beside a `.profile` switches that off.
        eprintln!(
            "\n{}",
            ui::dim(format!(
                "The last two are optional: switch JDK on cd, and tab completion.\n\
                 A login bash (what macOS terminals start) skips ~/.bashrc: there, use the\n\
                 first of {BASH_LOGIN_FILES} that exists, else ~/.bash_profile."
            ))
        );
        eprintln!("\n{}\n", ui::dim("Then load it into this shell:"));
        eprintln!("{}", ui::command(&format!(". {main}")));
        eprintln!(
            "\n{}",
            ui::dim("These lines never change: upgrades regenerate the files they point at.")
        );
    }
    path_nudge(symlink, home);
}

/// The files `bash -l` looks for, in the order it looks. It reads only the
/// first one that exists.
const BASH_LOGIN_FILES: &str = "~/.bash_profile, ~/.bash_login, ~/.profile";

/// Only when the symlink exists and `~/.local/bin` is not on PATH. Names its
/// files because `~/.zshrc`, beside the activation lines, is the one file the
/// non-interactive shells it is for never read; zsh reads `~/.zshenv` for `-c`
/// and `-lc` alike, and bash has no such file, so a login file is closest.
fn path_nudge(symlink: Option<&Path>, home: Option<&Path>) {
    let Some(link) = symlink else { return };
    let Some(dir) = link.parent() else { return };
    let on_path = std::env::var_os("PATH")
        .is_some_and(|path| std::env::split_paths(&path).any(|entry| entry == dir));
    if on_path {
        return;
    }
    // Dim: everything but the command is scaffolding.
    eprintln!(
        "\n{}\n",
        ui::dim(format!(
            "'jlo' also wants {} on PATH - for non-interactive shells\n\
             (CI, scripts, AI agents) and for 'jlo home'.",
            tilde(dir, home)
        ))
    );
    eprintln!(
        "{}\n",
        ui::dim(format!(
            "Add this line to ~/.zshenv, or for bash to the first of\n\
             {BASH_LOGIN_FILES} that exists, else ~/.bash_profile:"
        ))
    );
    eprintln!("{}", ui::command(PATH_LINE));
}

/// Runs in every nested shell, so it adds `~/.local/bin` only once, leaves no
/// stray colon on an empty PATH and is nounset-safe. It *appends*: prepending
/// would change which of the user's other tools in that directory win.
const PATH_LINE: &str = r#"case ":${PATH-}:" in *":$HOME/.local/bin:"*) ;; *) export PATH="${PATH:+$PATH:}$HOME/.local/bin" ;; esac"#;

/// A default install prints the unexpanded `"$HOME/.jlo/..."` so the same line
/// works on another machine; the generated files it points at hold the real
/// paths. A custom `JLO_HOME` is quoted like any other baked path, so a `$` in
/// it stays a `$`.
fn snippet(layout: &Layout, home: Option<&Path>, entry: &Entry) -> String {
    if home.is_some_and(|h| layout.home == h.join(crate::home::JLO_HOME_DIR_NAME)) {
        format!(
            "\"$HOME/{}/{}\"",
            crate::home::JLO_HOME_DIR_NAME,
            entry.name
        )
    } else {
        sq(&display(&layout.entry(entry)))
    }
}

fn source_line(path: &str) -> String {
    format!("[ -s {path} ] && . {path}")
}

/// Every value written into generated shell code is quoted: a `$`, a backtick
/// or a quote in a `JLO_HOME` path would otherwise be code.
use crate::shellenv::shell_quote as sq;

fn display(path: &Path) -> String {
    path.to_string_lossy().into_owned()
}

/// Write `contents` to `path` via a temp file **in `path`'s own directory**:
/// `rename` is only atomic within one filesystem, and a sibling is the only
/// placement that holds when `bin/` is a mount point or a symlink.
fn write_atomic(path: &Path, contents: &[u8]) -> Result<()> {
    let dir = path
        .parent()
        .ok_or_else(|| anyhow!("{path:?} has no parent directory."))?;
    let name = path
        .file_name()
        .ok_or_else(|| anyhow!("{path:?} has no file name."))?
        .to_string_lossy()
        .into_owned();
    let tmp = dir.join(format!(".{name}.tmp{}", std::process::id()));

    let staged = fs::File::create(&tmp).and_then(|mut f| {
        f.write_all(contents)?;
        f.sync_all()
    });
    if let Err(e) = staged {
        let _ = fs::remove_file(&tmp);
        return Err(anyhow!("could not write {path:?}: {e}."));
    }
    if let Err(e) = fs::rename(&tmp, path) {
        let _ = fs::remove_file(&tmp);
        return Err(anyhow!("could not write {path:?}: {e}."));
    }
    sync_dir(dir);
    Ok(())
}

/// Make a `rename` durable by flushing the *directory entry*. Best effort:
/// some filesystems refuse `fsync` on a directory, which is no reason to fail
/// an install.
fn sync_dir(dir: &Path) {
    if let Ok(handle) = fs::File::open(dir) {
        let _ = handle.sync_all();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn layout_at(home: &Path) -> Layout {
        Layout::curl(home.to_path_buf())
    }

    #[test]
    fn a_default_home_keeps_the_snippet_portable() {
        let home = Path::new("/home/u");
        let layout = layout_at(&home.join(".jlo"));
        assert_eq!(
            snippet(&layout, Some(home), &JLO_SH),
            "\"$HOME/.jlo/jlo.sh\""
        );
    }

    #[test]
    fn a_custom_home_is_spelled_out_and_quoted() {
        let home = Path::new("/home/u");
        let layout = layout_at(Path::new("/opt/jlo"));
        assert_eq!(snippet(&layout, Some(home), &JLO_SH), "'/opt/jlo/jlo.sh'");
    }

    #[test]
    fn write_atomic_leaves_no_temp_file_behind() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("jlo.sh");
        write_atomic(&path, b"hello\n").expect("write");
        assert_eq!(fs::read_to_string(&path).expect("read"), "hello\n");
        let leftovers: Vec<_> = fs::read_dir(dir.path())
            .expect("read_dir")
            .filter_map(Result::ok)
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n != "jlo.sh")
            .collect();
        assert!(
            leftovers.is_empty(),
            "temp files left behind: {leftovers:?}"
        );
    }
}
