on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust (if needed)
        run: rustup update

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

  deny:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Check advisories, licenses, bans and sources
        uses: EmbarkStudios/cargo-deny-action@v2

  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            package: jlo-linux-x86_64
          - os: macos-latest
            arch: aarch64
            package: jlo-macos-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust (if needed)
        run: rustup update

      - name: Build release
        run: cargo test --release
        env:
          RUST_BACKTRACE: full

      - name: Build package
        run: tar --no-same-owner -czf ${{ matrix.package }}.tar.gz jlo-autoload.sh jlo-init.sh -C target/release jlo-bin

      - name: Upload package
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.package }}-artifact
          path: jlo-*.tar.gz
